# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: .ci/gitlab/ci.yml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
    -   id: check-symlinks
    -   id: check-added-large-files
    -   id: debug-statements
        exclude: "src/pymor/algorithms/rules.py"
    -   id: pretty-format-json
        args: [--autofix]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.270'
  hooks:
    - id: ruff
      args: ["--fix"]
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.7.1
  hooks:
  - id: markdownlint-cli2
ci:
  autofix_prs: false
