name: Dependencies changed
on:
  push:
    paths:
      - 'dependencies.py'
      - '.ci/create_conda_env.py'
jobs:
  update:
    name: Update dependency files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyMOR-ci
          miniforge-variant: Mambaforge
          use-mamba: true
          python-version: 3.9
          channels: conda-forge
          channel-priority: true
      - name: Install dependencies
        run: pip install -r requirements-ci.txt
      - name: Update requirements
        run: python ./dependencies.py
      - name: Update env
        run: python .ci/create_conda_env.py requirements*.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update requirements and environments"
          commit_user_name: pyMOR Bot
          commit_user_email: ci@pymor.org
          commit_author: pyMOR Bot <ci@pymor.org>
          file_pattern: requirements*.txt .ci/conda-env.yml pyproject.toml
