name: Dependencies changed
on:
  pull_request:
    paths:
      - 'dependencies.py'
      - '.ci/create_conda_env.py'
jobs:
  update:
    name: Update dependency files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyMOR-ci
          miniforge-variant: Mambaforge
          use-mamba: true
          python-version: 3.9
          channels: conda-forge
          channel-priority: true
      - name: Install dependencies
        run: pip install -r requirements-ci.txt
      - name: Update requirements
        run: python ./dependencies.py
      - name: Update env
        run: python .ci/create_conda_env.py requirements*.txt
      - uses: peter-evans/create-pull-request@v4.2.3
        name: Create a PR for changed env
        with:
          commit-message: "[Bot] Update requirements and environments"
          title: "[Bot] Update requirements and environments"
          body: "Updates the conda environment for PR ${{ format('#{0}', github.event.pull_request.number) }}."
          author: pyMOR Bot <ci@pymor.org>
          labels: pr:change,infrastructure
          delete-branch: true
          branch-suffix: short-commit-hash
          base: ${{ github.head_ref }}
          assignees: ${{ github.event.pull_request.author.login }}
      - name: Upload Logfile
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: create_conda_env.log.txt
          path: .ci/create_conda_env.log
      - name: Upload new requirements
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: requirements
          path: requirements*.txt
  docker:
    name: Update docker images
    runs-on: ubuntu-22.04
    needs: update
    steps:
      - uses: actions/checkout@v3
        with:
          repository: pymor/docker
          ssh-key: ${{ secrets.PYMOR_DOCKER_DEPLOY }}
      - uses: actions/download-artifact@v3
        with:
          name: requirements
          path: ./constraints/
      - uses: peter-evans/create-pull-request@v4.2.3
        name: Create a PR for dependencies
        with:
          commit-message: "[Bot] Update requirements/constraints"
          title: "Update requirements for pymor PR ${{ format('{0}', github.event.pull_request.number) }}"
          body: "Update requirements PR ${{ format('https://github.com/{1}/pulls/{0}', github.event.pull_request.number, github.repository) }}"
          author: pyMOR Bot <ci@pymor.org>
          labels: pr:change,infrastructure
          delete-branch: true
          branch-suffix: short-commit-hash
          base: main
          assignees: ${{ github.event.pull_request.author.login }}
