name: Dependencies changed
on:
  push:
    paths:
      - 'dependencies.py'
      - '.ci/create_conda_env.py'
jobs:
  update:
    name: Update dependency files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyMOR-ci
          miniforge-variant: Mambaforge
          use-mamba: true
          python-version: 3.9
          channels: conda-forge
          channel-priority: true
      - name: Install dependencies
        run: pip install -r requirements-ci.txt
      - name: Update requirements
        run: python ./dependencies.py
      - name: Update env
        run: python .ci/create_conda_env.py requirements*.txt
      - uses: peter-evans/create-pull-request@v4.1.3
        name: Create a PR for changed env
        with:
          commit-message: "[Bot] Update requirements and environments"
          title: "[Bot] Update requirements and environments"
          author: pyMOR Bot <ci@pymor.org>
          labels: pr:change
          delete-branch: true
          branch-suffix: short-commit-hash
      - name: Upload Logfile
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: create_conda_env.log.txt
          path: .ci/create_conda_env.log
