name: PR Labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  # This action will triage pull requests and apply a label based on the
  # paths that are modified in the pull request.
  #
  # To use this workflow, you will need to set up a .github/labeler.yml
  # file with configuration.  For more information, see:
  # https://github.com/actions/labeler/blob/master/README.md
  autolabel:
    name: Auto-add
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
  #
  enforce-label:
    name: "Enforce pr:*"
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.2.2
      with:
        REQUIRED_LABELS_ANY: "pr:change,pr:deprecation,pr:fix,pr:new-feature,pr:removal"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label with a 'pr:' prefix for this pull request"
        BANNED_LABELS: "bug"
        BANNED_LABELS_DESCRIPTION: "The 'bug' label should only be used on issues"
