name: Linter

on:
  pull_request:

jobs:
  lint:
    name: run_linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: pip install -r requirements-ci.txt
    - name: Run flake8 linter
      run: |
        mkdir -p ./linter_output
        echo ${{ github.event.number }} > ./linter_output/pr_number
        echo ${{ github.event.pull_request.head.sha }} > ./linter_output/head_sha
        flake8 src | tee ./linter_output/flake8.out

    - uses: actions/upload-artifact@v3
      with:
        name: linter_output
        path: linter_output
