name: Process changed dependencies
on:
  workflow_run:
    workflows: ["Dependencies changed"]
    types:
      - completed

jobs:
  get_info:
    name: "Get information about the source run"
    runs-on: ubuntu-latest
    outputs:
      pullRequestNumber: ${{ steps.source-run-info.outputs.pullRequestNumber }}
    steps:
      - name: "Get information about the origin 'CI' run"
        uses: potiuk/get-workflow-origin@v1_5
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

  docker:
    name: Update docker images
    runs-on: ubuntu-22.04
    needs: [get_info]
    outputs:
      pr_url: ${{ steps.create_pr.outputs.pull-request-url }}
      env_sha: ${{ steps.create_pr.outputs.pull-request-head-sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: pymor/docker
          ssh-key: ${{ secrets.PYMOR_DOCKER_DEPLOY }}
      - uses: dawidd6/action-download-artifact@v2.24.3
        with:
          workflow: dependencies_change.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: requirements
          path: ./constraints/
      - uses: peter-evans/create-pull-request@v4.2.3
        name: Create a PR for dependencies
        id: create_pr
        with:
          commit-message: "[Bot] Update requirements/constraints"
          title: "Update requirements for pymor PR ${{ format('{0}', needs.get_info.outputs.pullRequestNumber) }}"
          body: "Update requirements PR ${{ format('https://github.com/{1}/pull/{0}', needs.get_info.outputs.pullRequestNumber, github.repository) }}"
          author: pyMOR Bot <ci@pymor.org>
          token: ${{ secrets.PYMOR_DOCKER_PR_TOKEN }}
          add-paths: constraints/requirements*.txt
          labels: automerge
          delete-branch: true
          branch: update-requirements-${{ needs.get_info.outputs.pullRequestNumber }}
          base: main

  create_pr:
    name: Create PR
    runs-on: ubuntu-22.04
    needs: [docker, get_info]
    outputs:
      pr_url: ${{ steps.create_pr.outputs.pull-request-url }}
      env_sha: ${{ steps.create_pr.outputs.pull-request-head-sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: dawidd6/action-download-artifact@v2.24.3
        with:
          workflow: dependencies_change.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: conda_env
          path: ./.ci/
      - run: pip install -r requirements-ci.txt
      - name: Update .env
        env:
          ENV_SHA: ${{ needs.docker.outputs.env_sha }}
        run: |
          if [[ ${ENV_SHA} != "" ]]; then
            sed -i "/^PYPI_MIRROR_TAG/s/=.*$/=${ENV_SHA}/" .env
            sed -i "/^CI_IMAGE_TAG/s/=.*$/=${ENV_SHA}/" .env
          fi
      - name: Regenerate template
        run: make template
      - run: git diff
      - uses: peter-evans/create-pull-request@v4.2.3
        name: Create a PR for changed env
        id: create_pr
        with:
          commit-message: "[Bot] Update requirements and environments"
          title: "[Bot] Update requirements and environments"
          body: |
            Updates the conda environment / docker images for PR ${{ format('#{0}', needs.get_info.outputs.pullRequestNumber) }}.
            The Gitlab pipelines of this PR might need to be restarted once ${{ needs.docker.outputs.pr_url }}
            is merged/finished.
          author: pyMOR Bot <ci@pymor.org>
          labels: pr:change,infrastructure,dependencies,automerge
          delete-branch: true
          branch: update-requirements-${{ needs.get_info.outputs.pullRequestNumber }}
          base: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: PR Comment
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ steps.create_pr.outputs.pull-request-number }}
        with:
          pr_number: ${{ needs.get_info.outputs.pullRequestNumber }}
          comment_tag: "pr_comment_pymor"
          message: |
            Please wait for ${{ steps.create_pr.outputs.pull-request-url }} to be merged before merging this PR.
          reactions: rocket
